package rekammedis;

import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.util.UIScale;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.DefaultTableCellRenderer;

public class DlgRiwayatLab extends javax.swing.JDialog {
    private final DefaultTableModel tabMode;
    private final sekuel Sequel = new sekuel();
    private final validasi Valid = new validasi();
    private Connection koneksi = koneksiDB.condb();
    private PreparedStatement ps;
    private ResultSet rs;
    private String no_rkm_medis = "";

    /**
     * Creates new form DlgRiwayatLab
     * @param parent
     * @param modal
     */
    public DlgRiwayatLab(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        // --- [MODERNISASI] ---
        // Mengubah tampilan agar lebih modern
        setupModernUI();

        Object[] row = {"Tgl. Periksa", "Jam", "No. Rawat", "Pemeriksaan", "Item Pemeriksaan", "Hasil", "Satuan", "Nilai Rujukan", "Keterangan"};
        tabMode = new DefaultTableModel(null, row) {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        tbRiwayat.setModel(tabMode);
        
        // --- [MODERNISASI] ---
        // Mengatur tampilan tabel
        setupTable();
    }
    
    private void setupModernUI() {
        // Memberi padding pada panel atas
        panelGlass1.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        
        // Memberi border pada scroll pane
        scrollPane1.setBorder(BorderFactory.createLineBorder(new Color(220, 220, 220)));

        // Mengatur font default
        tbRiwayat.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tbRiwayat.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        
        // Membuat TNoRM1 terlihat seperti label (read-only)
        TNoRM1.setFocusable(false);
        TNoRM1.setBackground(UIManager.getColor("TextField.disabledBackground"));
    }
    
    private void setupTable() {
        tbRiwayat.setPreferredScrollableViewportSize(new Dimension(800, 800));
        tbRiwayat.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        for (int i = 0; i < 9; i++) {
            TableColumn column = tbRiwayat.getColumnModel().getColumn(i);
            if (i == 0) column.setPreferredWidth(85);   // Tgl. Periksa
            else if (i == 1) column.setPreferredWidth(65);  // Jam
            else if (i == 2) column.setPreferredWidth(130); // No. Rawat
            else if (i == 3) column.setPreferredWidth(220); // Pemeriksaan
            else if (i == 4) column.setPreferredWidth(230); // Item Pemeriksaan
            else if (i == 5) column.setPreferredWidth(110); // Hasil
            else if (i == 6) column.setPreferredWidth(80);  // Satuan
            else if (i == 7) column.setPreferredWidth(160); // Nilai Rujukan
            else if (i == 8) column.setPreferredWidth(180); // Keterangan
        }
        
        // Menerapkan custom renderer yang telah diperbarui
        tbRiwayat.setDefaultRenderer(Object.class, new ModernTableRenderer());
        tbRiwayat.setRowHeight(24); // Menambah tinggi baris agar tidak terlalu rapat
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        panelGlass1 = new widget.panelisi();
        jLabel1 = new widget.Label();
        TNoRM = new widget.TextBox();
        TNoRM1 = new widget.TextBox();
        BtnCari = new widget.Button();
        BtnKeluar = new widget.Button();
        scrollPane1 = new widget.ScrollPane();
        tbRiwayat = new widget.Table();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("::[ Riwayat Pemeriksaan Laboratorium Pasien ]::");
        setUndecorated(true);
        setResizable(false);

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 225, 215)), "Riwayat Pemeriksaan Laboratorium Pasien", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout());

        panelGlass1.setName("panelGlass1"); // NOI18N
        panelGlass1.setPreferredSize(new java.awt.Dimension(44, 55));
        panelGlass1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 8, 5));

        jLabel1.setText("No. Rekam Medis :");
        jLabel1.setName("jLabel1"); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(110, 23));
        panelGlass1.add(jLabel1);

        TNoRM.setName("TNoRM"); // NOI18N
        TNoRM.setPreferredSize(new java.awt.Dimension(120, 23));
        TNoRM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TNoRMKeyPressed(evt);
            }
        });
        panelGlass1.add(TNoRM);

        TNoRM1.setEditable(false);
        TNoRM1.setName("TNoRM1"); // NOI18N
        TNoRM1.setPreferredSize(new java.awt.Dimension(280, 23));
        panelGlass1.add(TNoRM1);

        BtnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        BtnCari.setMnemonic('C');
        BtnCari.setText("Tampilkan");
        BtnCari.setToolTipText("Alt+C");
        BtnCari.setName("BtnCari"); // NOI18N
        BtnCari.setPreferredSize(new java.awt.Dimension(120, 30));
        BtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariActionPerformed(evt);
            }
        });
        panelGlass1.add(BtnCari);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        panelGlass1.add(BtnKeluar);

        internalFrame1.add(panelGlass1, java.awt.BorderLayout.PAGE_START);

        scrollPane1.setName("scrollPane1"); // NOI18N
        scrollPane1.setOpaque(true);

        tbRiwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbRiwayat.setName("tbRiwayat"); // NOI18N
        scrollPane1.setViewportView(tbRiwayat);

        internalFrame1.add(scrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>

    private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {
        if (TNoRM.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Silakan masukkan Nomor Rekam Medis terlebih dahulu.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else {
            this.no_rkm_medis = TNoRM.getText();
            TNoRM1.setText(Sequel.cariIsi("select nm_pasien from pasien where no_rkm_medis=?", no_rkm_medis));
            if (TNoRM1.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Data pasien tidak ditemukan.", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
            tampilRiwayat();
        }
    }

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
    }

    private void TNoRMKeyPressed(java.awt.event.KeyEvent evt) {
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            BtnCariActionPerformed(null);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* --- [MODERNISASI] --- */
        // Mengatur Look and Feel FlatLaf
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
            // Optional: Mengatur font default untuk semua komponen
            UIManager.put("defaultFont", new Font("Segoe UI", Font.PLAIN, 12));
        } catch (Exception ex) {
            System.err.println("Gagal menginisialisasi LaF: " + ex.getMessage());
        }

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            DlgRiwayatLab dialog = new DlgRiwayatLab(new javax.swing.JFrame(), true);
            /*
            PERBAIKAN: Listener di bawah ini menyebabkan seluruh aplikasi keluar.
            Ini hanya boleh digunakan saat menjalankan file ini secara mandiri untuk testing.
            Karena dapat menyebabkan masalah saat dipanggil dari jendela lain,
            maka bagian ini dikomentari/dihapus.
            */
            // dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            //     @Override
            //     public void windowClosing(java.awt.event.WindowEvent e) {
            //         System.exit(0);
            //     }
            // });
            dialog.setLocationRelativeTo(null); // Menampilkan dialog di tengah layar
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify
    private widget.Button BtnCari;
    private widget.Button BtnKeluar;
    private widget.TextBox TNoRM;
    private widget.TextBox TNoRM1;
    private widget.InternalFrame internalFrame1;
    private widget.Label jLabel1;
    private widget.panelisi panelGlass1;
    private widget.ScrollPane scrollPane1;
    private widget.Table tbRiwayat;
    // End of variables declaration

    private void tampilRiwayat() {
        Valid.tabelKosong(tabMode);
        try {
            ps = koneksi.prepareStatement(
                "SELECT pl.tgl_periksa, pl.jam, pl.no_rawat, jpl.nm_perawatan, tl.Pemeriksaan, " +
                "dpl.nilai, tl.satuan, dpl.nilai_rujukan, dpl.keterangan " +
                "FROM periksa_lab pl " +
                "INNER JOIN reg_periksa rp ON pl.no_rawat = rp.no_rawat " +
                "INNER JOIN jns_perawatan_lab jpl ON pl.kd_jenis_prw = jpl.kd_jenis_prw " +
                "INNER JOIN detail_periksa_lab dpl ON pl.no_rawat = dpl.no_rawat AND pl.tgl_periksa = dpl.tgl_periksa AND pl.jam = dpl.jam AND pl.kd_jenis_prw = dpl.kd_jenis_prw " +
                "INNER JOIN template_laboratorium tl ON dpl.id_template = tl.id_template " +
                "WHERE rp.no_rkm_medis = ? AND pl.kategori='PK' " +
                "ORDER BY pl.tgl_periksa DESC, pl.jam DESC, jpl.nm_perawatan, tl.urut"
            );
            
            try {
                ps.setString(1, no_rkm_medis);
                rs = ps.executeQuery();
                String lastDate = ""; 
                while (rs.next()) {
                    String currentDate = rs.getString("tgl_periksa");
                    if (!lastDate.equals(currentDate) && !lastDate.isEmpty()) {
                        // Tambahkan baris pemisah dengan penanda khusus
                        tabMode.addRow(new Object[]{"SEPARATOR", "", "", "", "", "", "", "", ""}); 
                    }
                    
                    tabMode.addRow(new Object[]{
                        currentDate,
                        rs.getString("jam"),
                        rs.getString("no_rawat"),
                        rs.getString("nm_perawatan"),
                        rs.getString("Pemeriksaan"),
                        rs.getString("nilai"),
                        rs.getString("satuan"),
                        rs.getString("nilai_rujukan"),
                        rs.getString("keterangan")
                    });
                    
                    lastDate = currentDate;
                }
            } catch (SQLException e) {
                System.out.println("Notifikasi Riwayat Lab: " + e);
            } finally {
                if (rs != null) rs.close();
                if (ps != null) ps.close();
            }
        } catch (SQLException e) {
            System.out.println("Notifikasi Kueri Riwayat: " + e);
        }
    }
    
    public void setNoRm(String noRm, String namaPasien) {
        this.no_rkm_medis = noRm;
        TNoRM.setText(noRm);
        TNoRM1.setText(namaPasien);
        tampilRiwayat();
    }

    /**
     * --- [MODERNISASI] ---
     * Class internal untuk mewarnai tabel dengan gaya modern.
     * Menggunakan DefaultTableCellRenderer untuk efisiensi.
     */
    public class ModernTableRenderer extends DefaultTableCellRenderer {
        private final Color ABNORMAL_COLOR = new Color(200, 0, 0); // Merah tua
        private final Color NORMAL_COLOR = Color.BLACK;
        private final Color ROW_ALT_COLOR = new Color(245, 245, 245); // Abu-abu sangat muda
        private final Color SEPARATOR_COLOR = new Color(225, 235, 255); // Biru muda
        
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            Component component = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            
            // Cek untuk baris pemisah
            if (table.getValueAt(row, 0) != null && table.getValueAt(row, 0).toString().equals("SEPARATOR")) {
                component.setBackground(SEPARATOR_COLOR);
                // Mengosongkan teks pada baris pemisah
                if (component instanceof JComponent) {
                    ((JComponent) component).setBorder(BorderFactory.createEmptyBorder(0,0,0,0));
                }
                setText(""); // Tidak menampilkan teks "SEPARATOR"
                return component;
            }

            // Mengatur warna latar belakang selang-seling (zebra)
            if (!isSelected) {
                component.setBackground(row % 2 == 0 ? Color.WHITE : ROW_ALT_COLOR);
            }
            
            // Default warna teks
            component.setForeground(NORMAL_COLOR);
            
            try {
                String hasilStr = table.getValueAt(row, 5) != null ? table.getValueAt(row, 5).toString().trim() : "";
                String rujukanStr = table.getValueAt(row, 7) != null ? table.getValueAt(row, 7).toString().trim() : "";
                
                if (hasilStr.isEmpty() || rujukanStr.isEmpty() || rujukanStr.equalsIgnoreCase("normal") || rujukanStr.equalsIgnoreCase("negatif")) {
                    // Jika rujukan adalah teks standar atau hasil kosong, tidak perlu diwarnai
                } else {
                    boolean isAbnormal = checkAbnormal(hasilStr, rujukanStr);
                    if (isAbnormal) {
                        component.setForeground(ABNORMAL_COLOR);
                    }
                }
            } catch (Exception e) {
                // Abaikan jika ada error saat parsing, biarkan warna default
            }

            return component;
        }
        
        private boolean checkAbnormal(String hasil, String rujukan) {
            try {
                // 1. Cek untuk rentang numerik (e.g., "10.0 - 20.5")
                if (rujukan.contains("-")) {
                    String[] parts = rujukan.split("-");
                    if (parts.length == 2) {
                        double lowerBound = Double.parseDouble(parts[0].trim());
                        double upperBound = Double.parseDouble(parts[1].trim());
                        double nilaiHasil = Double.parseDouble(hasil);
                        return nilaiHasil < lowerBound || nilaiHasil > upperBound;
                    }
                // 2. Cek untuk batas atas (e.g., "<150")
                } else if (rujukan.startsWith("<")) {
                    double upperBound = Double.parseDouble(rujukan.replace("<", "").trim());
                    double nilaiHasil = Double.parseDouble(hasil);
                    return nilaiHasil >= upperBound;
                // 3. Cek untuk batas bawah (e.g., ">50")
                } else if (rujukan.startsWith(">")) {
                    double lowerBound = Double.parseDouble(rujukan.replace(">", "").trim());
                    double nilaiHasil = Double.parseDouble(hasil);
                    return nilaiHasil <= lowerBound;
                }
            } catch (NumberFormatException e) {
                // Jika parsing gagal, bandingkan sebagai string (case-insensitive)
                return !hasil.equalsIgnoreCase(rujukan);
            }
            // Jika tidak ada kondisi di atas, bandingkan sebagai string
            return !hasil.equalsIgnoreCase(rujukan);
        }
    }
}