/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rekammedis;

import fungsi.WarnaTable;
import fungsi.batasInput;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.akses;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Pallicks
 */
public class DlgRiwayatKonsultasi extends javax.swing.JDialog {

    private final DefaultTableModel tabMode;
    private Connection koneksi = koneksiDB.condb();
    private sekuel Sequel = new sekuel();
    private validasi Valid = new validasi();
    private PreparedStatement ps;
    private ResultSet rs;
    private int i = 0;
    private String no_rkm_medis = "";
    private StringBuilder htmlContent;

    /**
     * Creates new form DlgRiwayatKonsultasi
     *
     * @param parent
     * @param modal
     */
    public DlgRiwayatKonsultasi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        tabMode = new DefaultTableModel(null, new Object[]{
            "No.Permintaan", "No.Rawat", "No.RM", "Nama Pasien", "Tgl. Konsultasi", "Permintaan",
            "Kode Dokter Konsul", "Dokter Yg Meminta", "Kode Dokter Dikonsuli", "Dokter Tujuan", "Diagnosa Kerja Konsul",
            "Uraian Konsultasi", "Tgl. Jawaban", "Diagnosa Kerja Jawaban", "Jawaban Konsultasi"
        }) {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        tbRiwayat.setModel(tabMode);

        tbRiwayat.setPreferredScrollableViewportSize(new Dimension(500, 500));
        tbRiwayat.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        for (i = 0; i < 15; i++) {
            TableColumn column = tbRiwayat.getColumnModel().getColumn(i);
            if (i == 0) {
                column.setPreferredWidth(105);
            } else if (i == 1) {
                column.setPreferredWidth(105);
            } else if (i == 2) {
                column.setPreferredWidth(70);
            } else if (i == 3) {
                column.setPreferredWidth(150);
            } else if (i == 4) {
                column.setPreferredWidth(115);
            } else if (i == 5) {
                column.setPreferredWidth(100);
            } else if (i == 6) {
                column.setMinWidth(0);
                column.setMaxWidth(0);
            } else if (i == 7) {
                column.setPreferredWidth(160);
            } else if (i == 8) {
                column.setMinWidth(0);
                column.setMaxWidth(0);
            } else if (i == 9) {
                column.setPreferredWidth(160);
            } else if (i == 10) {
                column.setPreferredWidth(200);
            } else if (i == 11) {
                column.setPreferredWidth(350);
            } else if (i == 12) {
                column.setPreferredWidth(115);
            } else if (i == 13) {
                column.setPreferredWidth(200);
            } else if (i == 14) {
                column.setPreferredWidth(350);
            }
        }
        tbRiwayat.setDefaultRenderer(Object.class, new WarnaTable());

        TCari.setDocument(new batasInput((int) 100).getKata(TCari));
        if (koneksiDB.CARICEPAT().equals("aktif")) {
            TCari.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
                @Override
                public void insertUpdate(DocumentEvent e) {
                    if (TCari.getText().length() > 2) {
                        tampil();
                    }
                }

                @Override
                public void removeUpdate(DocumentEvent e) {
                    if (TCari.getText().length() > 2) {
                        tampil();
                    }
                }

                @Override
                public void changedUpdate(DocumentEvent e) {
                    if (TCari.getText().length() > 2) {
                        tampil();
                    }
                }
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        jSplitPane1 = new javax.swing.JSplitPane();
        Scroll = new widget.ScrollPane();
        tbRiwayat = new widget.Table();
        ScrollDetail = new widget.ScrollPane();
        DetailKonsultasi = new widget.TextArea();
        jPanel3 = new javax.swing.JPanel();
        panelGlass8 = new widget.panelisi();
        BtnPrint = new widget.Button();
        BtnKeluar = new widget.Button();
        panelGlass10 = new widget.panelisi();
        jLabel6 = new widget.Label();
        TCari = new widget.TextBox();
        BtnCari = new widget.Button();
        BtnAll = new widget.Button();
        jLabel7 = new widget.Label();
        LCount = new widget.Label();
        panelCari = new widget.panelisi();
        jLabel15 = new widget.Label();
        DTPCari1 = new widget.Tanggal();
        jLabel25 = new widget.Label();
        DTPCari2 = new widget.Tanggal();
        jLabel10 = new widget.Label();
        TNoRM = new widget.TextBox();
        TPasien = new widget.TextBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0), 4), "::[ Riwayat Konsultasi Medik Pasien ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 3, 18), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setResizeWeight(0.5);
        jSplitPane1.setOneTouchExpandable(true);

        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);

        tbRiwayat.setAutoCreateRowSorter(true);
        tbRiwayat.setToolTipText("Silahkan klik untuk memilih data yang akan dilihat detailnya");
        tbRiwayat.setName("tbRiwayat"); // NOI18N
        tbRiwayat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbRiwayatMouseClicked(evt);
            }
        });
        tbRiwayat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbRiwayatKeyReleased(evt);
            }
        });
        Scroll.setViewportView(tbRiwayat);

        jSplitPane1.setTopComponent(Scroll);

        ScrollDetail.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Detail Konsultasi ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11))); // NOI18N
        ScrollDetail.setName("ScrollDetail"); // NOI18N
        ScrollDetail.setOpaque(true);

        DetailKonsultasi.setEditable(false);
        DetailKonsultasi.setColumns(20);
        DetailKonsultasi.setRows(5);
        DetailKonsultasi.setName("DetailKonsultasi"); // NOI18N
        ScrollDetail.setViewportView(DetailKonsultasi);

        jSplitPane1.setBottomComponent(ScrollDetail);

        internalFrame1.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(44, 100));
        jPanel3.setLayout(new java.awt.BorderLayout(1, 1));

        panelGlass8.setName("panelGlass8"); // NOI18N
        panelGlass8.setPreferredSize(new java.awt.Dimension(55, 55));
        panelGlass8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        BtnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/b_print.png"))); // NOI18N
        BtnPrint.setMnemonic('T');
        BtnPrint.setText("Cetak");
        BtnPrint.setToolTipText("Alt+T");
        BtnPrint.setName("BtnPrint"); // NOI18N
        BtnPrint.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrintActionPerformed(evt);
            }
        });
        BtnPrint.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnPrintKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnPrint);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnKeluar);

        jPanel3.add(panelGlass8, java.awt.BorderLayout.CENTER);

        panelGlass10.setName("panelGlass10"); // NOI18N
        panelGlass10.setPreferredSize(new java.awt.Dimension(44, 44));
        panelGlass10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        jLabel6.setText("Key Word :");
        jLabel6.setName("jLabel6"); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(70, 23));
        panelGlass10.add(jLabel6);

        TCari.setName("TCari"); // NOI18N
        TCari.setPreferredSize(new java.awt.Dimension(450, 23));
        TCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TCariKeyPressed(evt);
            }
        });
        panelGlass10.add(TCari);

        BtnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        BtnCari.setMnemonic('2');
        BtnCari.setToolTipText("Alt+2");
        BtnCari.setName("BtnCari"); // NOI18N
        BtnCari.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariActionPerformed(evt);
            }
        });
        BtnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCariKeyPressed(evt);
            }
        });
        panelGlass10.add(BtnCari);

        BtnAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search-16x16.png"))); // NOI18N
        BtnAll.setMnemonic('M');
        BtnAll.setToolTipText("Alt+M");
        BtnAll.setName("BtnAll"); // NOI18N
        BtnAll.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAllActionPerformed(evt);
            }
        });
        BtnAll.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAllKeyPressed(evt);
            }
        });
        panelGlass10.add(BtnAll);

        jLabel7.setText("Record :");
        jLabel7.setName("jLabel7"); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(65, 23));
        panelGlass10.add(jLabel7);

        LCount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LCount.setText("0");
        LCount.setName("LCount"); // NOI18N
        LCount.setPreferredSize(new java.awt.Dimension(50, 23));
        panelGlass10.add(LCount);

        jPanel3.add(panelGlass10, java.awt.BorderLayout.PAGE_END);

        internalFrame1.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        panelCari.setName("panelCari"); // NOI18N
        panelCari.setPreferredSize(new java.awt.Dimension(44, 43));
        panelCari.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 9));

        jLabel15.setName("jLabel15"); // NOI18N
        jLabel15.setPreferredSize(new java.awt.Dimension(30, 23));
        panelCari.add(jLabel15);

        DTPCari1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "21-08-2025" }));
        DTPCari1.setDisplayFormat("dd-MM-yyyy");
        DTPCari1.setName("DTPCari1"); // NOI18N
        DTPCari1.setOpaque(false);
        DTPCari1.setPreferredSize(new java.awt.Dimension(95, 23));
        panelCari.add(DTPCari1);

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("s.d");
        jLabel25.setName("jLabel25"); // NOI18N
        jLabel25.setPreferredSize(new java.awt.Dimension(30, 23));
        panelCari.add(jLabel25);

        DTPCari2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "21-08-2025" }));
        DTPCari2.setDisplayFormat("dd-MM-yyyy");
        DTPCari2.setName("DTPCari2"); // NOI18N
        DTPCari2.setOpaque(false);
        DTPCari2.setPreferredSize(new java.awt.Dimension(95, 23));
        panelCari.add(DTPCari2);

        jLabel10.setText("Pasien :");
        jLabel10.setName("jLabel10"); // NOI18N
        jLabel10.setPreferredSize(new java.awt.Dimension(55, 23));
        panelCari.add(jLabel10);

        TNoRM.setEditable(false);
        TNoRM.setName("TNoRM"); // NOI18N
        TNoRM.setPreferredSize(new java.awt.Dimension(100, 23));
        panelCari.add(TNoRM);

        TPasien.setEditable(false);
        TPasien.setName("TPasien"); // NOI18N
        TPasien.setPreferredSize(new java.awt.Dimension(250, 23));
        panelCari.add(TPasien);

        internalFrame1.add(panelCari, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>                        

    private void BtnPrintActionPerformed(java.awt.event.ActionEvent evt) {                                         
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        if (tabMode.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Maaf, data sudah habis. Tidak ada data yang bisa anda print...!!!!");
        } else if (tabMode.getRowCount() != 0) {
            try {
                htmlContent = new StringBuilder();
                htmlContent.append(
                        "<tr class='isi'>"
                        + "<td valign='middle' bgcolor='#FFFAFA' align='center'><b>No.Permintaan</b></td>"
                        + "<td valign='middle' bgcolor='#FFFAFA' align='center'><b>No.Rawat</b></td>"
                        + "<td valign='middle' bgcolor='#FFFAFA' align='center'><b>Pasien</b></td>"
                        + "<td valign='middle' bgcolor='#FFFAFA' align='center'><b>Tgl. Konsultasi</b></td>"
                        + "<td valign='middle' bgcolor='#FFFAFA' align='center'><b>Permintaan</b></td>"
                        + "<td valign='middle' bgcolor='#FFFAFA' align='center'><b>Dokter Konsul</b></td>"
                        + "<td valign='middle' bgcolor='#FFFAFA' align='center'><b>Dokter Dikonsuli</b></td>"
                        + "<td valign='middle' bgcolor='#FFFAFA' align='center'><b>Diagnosa Kerja Konsul</b></td>"
                        + "<td valign='middle' bgcolor='#FFFAFA' align='center'><b>Uraian Konsultasi</b></td>"
                        + "<td valign='middle' bgcolor='#FFFAFA' align='center'><b>Tgl. Jawaban</b></td>"
                        + "<td valign='middle' bgcolor='#FFFAFA' align='center'><b>Diagnosa Kerja Jawaban</b></td>"
                        + "<td valign='middle' bgcolor='#FFFAFA' align='center'><b>Jawaban Konsultasi</b></td>"
                        + "</tr>"
                );
                for (i = 0; i < tabMode.getRowCount(); i++) {
                    htmlContent.append(
                            "<tr class='isi'>"
                            + "<td valign='top'>" + tbRiwayat.getValueAt(i, 0).toString() + "</td>"
                            + "<td valign='top'>" + tbRiwayat.getValueAt(i, 1).toString() + "</td>"
                            + "<td valign='top'>" + tbRiwayat.getValueAt(i, 2).toString() + " " + tbRiwayat.getValueAt(i, 3).toString() + "</td>"
                            + "<td valign='top'>" + tbRiwayat.getValueAt(i, 4).toString() + "</td>"
                            + "<td valign='top'>" + tbRiwayat.getValueAt(i, 5).toString() + "</td>"
                            + "<td valign='top'>" + tbRiwayat.getValueAt(i, 7).toString() + "</td>"
                            + "<td valign='top'>" + tbRiwayat.getValueAt(i, 9).toString() + "</td>"
                            + "<td valign='top'>" + tbRiwayat.getValueAt(i, 10).toString() + "</td>"
                            + "<td valign='top'>" + tbRiwayat.getValueAt(i, 11).toString() + "</td>"
                            + "<td valign='top'>" + tbRiwayat.getValueAt(i, 12).toString() + "</td>"
                            + "<td valign='top'>" + tbRiwayat.getValueAt(i, 13).toString() + "</td>"
                            + "<td valign='top'>" + tbRiwayat.getValueAt(i, 14).toString() + "</td>"
                            + "</tr>");
                }
                
                File f = new File("DataKonsultasiMedik.html");
                BufferedWriter bw = new BufferedWriter(new FileWriter(f));
                bw.write("<html><head><title></title><meta http-equiv='Content-Type' content='text/html; charset=iso-8859-1'/><link href='css/default.css' rel='stylesheet' type='text/css'/></head><body><center>" +
                         "<table width='1800px' border='0' align='center' cellpadding='1px' cellspacing='0' class='tbl_form'>" +
                         "<tr class='isi2'><td valign='top' align='center'>" +
                         "<font size='4' face='Tahoma'>" + akses.getnamars() + "</font><br>" +
                         akses.getalamatrs() + ", " + akses.getkabupatenrs() + ", " + akses.getpropinsirs() + "<br>" +
                         akses.getkontakrs() + ", E-mail : " + akses.getemailrs() + "<br><br>" +
                         "<font size='2' face='Tahoma'>RIWAYAT KONSULTASI MEDIK<br><br></font>" +
                         "</td></tr></table>" +
                         "<table width='1800px' border='0' align='center' cellpadding='1px' cellspacing='0' class='tbl_form'>" +
                         htmlContent.toString() +
                         "</table></center></body></html>");
                bw.close();
                Desktop.getDesktop().browse(f.toURI());

            } catch (Exception e) {
                System.out.println("Notifikasi : " + e);
            }
        }
        this.setCursor(Cursor.getDefaultCursor());
    }                                        

    private void BtnPrintKeyPressed(java.awt.event.KeyEvent evt) {                                    
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            BtnPrintActionPerformed(null);
        } else {
            Valid.pindah(evt, TCari, BtnKeluar);
        }
    }                                   

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        dispose();
    }                                         

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {                                     
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            dispose();
        } else {
            Valid.pindah(evt, BtnPrint, TCari);
        }
    }                                    

    private void TCariKeyPressed(java.awt.event.KeyEvent evt) {                                 
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            BtnCariActionPerformed(null);
        } else if (evt.getKeyCode() == KeyEvent.VK_PAGE_DOWN) {
            BtnCari.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_PAGE_UP) {
            BtnKeluar.requestFocus();
        }
    }                                

    private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {                                        
        tampil();
    }                                       

    private void BtnCariKeyPressed(java.awt.event.KeyEvent evt) {                                   
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            BtnCariActionPerformed(null);
        } else {
            Valid.pindah(evt, TCari, BtnAll);
        }
    }                                  

    private void BtnAllActionPerformed(java.awt.event.ActionEvent evt) {                                       
        TCari.setText("");
        tampil();
    }                                      

    private void BtnAllKeyPressed(java.awt.event.KeyEvent evt) {                                  
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            tampil();
            TCari.setText("");
        } else {
            Valid.pindah(evt, BtnCari, DTPCari1);
        }
    }                                 

    private void tbRiwayatMouseClicked(java.awt.event.MouseEvent evt) {                                       
        if (tabMode.getRowCount() != 0) {
            try {
                getData();
            } catch (java.lang.NullPointerException e) {
            }
        }
    }                                      

    private void tbRiwayatKeyReleased(java.awt.event.KeyEvent evt) {                                      
        if (tabMode.getRowCount() != 0) {
            if ((evt.getKeyCode() == KeyEvent.VK_UP) || (evt.getKeyCode() == KeyEvent.VK_DOWN)) {
                try {
                    getData();
                } catch (java.lang.NullPointerException e) {
                }
            }
        }
    }                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgRiwayatKonsultasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgRiwayatKonsultasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgRiwayatKonsultasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgRiwayatKonsultasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgRiwayatKonsultasi dialog = new DlgRiwayatKonsultasi(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private widget.Button BtnAll;
    private widget.Button BtnCari;
    private widget.Button BtnKeluar;
    private widget.Button BtnPrint;
    private widget.Tanggal DTPCari1;
    private widget.Tanggal DTPCari2;
    private widget.TextArea DetailKonsultasi;
    private widget.Label LCount;
    private widget.ScrollPane Scroll;
    private widget.ScrollPane ScrollDetail;
    private widget.TextBox TCari;
    private widget.TextBox TNoRM;
    private widget.TextBox TPasien;
    private widget.InternalFrame internalFrame1;
    private widget.Label jLabel10;
    private widget.Label jLabel15;
    private widget.Label jLabel25;
    private widget.Label jLabel6;
    private widget.Label jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSplitPane jSplitPane1;
    private widget.panelisi panelCari;
    private widget.panelisi panelGlass10;
    private widget.panelisi panelGlass8;
    private widget.Table tbRiwayat;
    // End of variables declaration                   

    public void tampil() {
        Valid.tabelKosong(tabMode);
        try {
            String sql = "SELECT konsultasi_medik.no_permintaan, konsultasi_medik.no_rawat, reg_periksa.no_rkm_medis, " +
                         "pasien.nm_pasien, konsultasi_medik.tanggal AS tanggalkonsultasi, " +
                         "konsultasi_medik.jenis_permintaan, konsultasi_medik.kd_dokter, dokterkonsul.nm_dokter AS dokterkonsul, " +
                         "konsultasi_medik.kd_dokter_dikonsuli, dokterdikonsuli.nm_dokter AS dokterdikonsuli, " +
                         "konsultasi_medik.diagnosa_kerja AS diagnosakerjakonsul, konsultasi_medik.uraian_konsultasi, " +
                         "jawaban_konsultasi_medik.tanggal AS tanggaljawaban, jawaban_konsultasi_medik.diagnosa_kerja AS diagnosakerjajawaban, " +
                         "jawaban_konsultasi_medik.uraian_jawaban " +
                         "FROM konsultasi_medik " +
                         "INNER JOIN reg_periksa ON konsultasi_medik.no_rawat = reg_periksa.no_rawat " +
                         "INNER JOIN pasien ON reg_periksa.no_rkm_medis = pasien.no_rkm_medis " +
                         "INNER JOIN dokter AS dokterkonsul ON konsultasi_medik.kd_dokter = dokterkonsul.kd_dokter " +
                         "INNER JOIN dokter AS dokterdikonsuli ON konsultasi_medik.kd_dokter_dikonsuli = dokterdikonsuli.kd_dokter " +
                         "LEFT JOIN jawaban_konsultasi_medik ON jawaban_konsultasi_medik.no_permintaan = konsultasi_medik.no_permintaan " +
                         "WHERE reg_periksa.no_rkm_medis = ? AND konsultasi_medik.tanggal BETWEEN ? AND ? AND " +
                         "(konsultasi_medik.no_permintaan LIKE ? OR konsultasi_medik.no_rawat LIKE ? OR pasien.nm_pasien LIKE ? OR " +
                         "dokterkonsul.nm_dokter LIKE ? OR dokterdikonsuli.nm_dokter LIKE ?) " +
                         "ORDER BY konsultasi_medik.tanggal DESC";
                         
            ps = koneksi.prepareStatement(sql);
            try {
                String keyword = "%" + TCari.getText().trim() + "%";
                ps.setString(1, this.no_rkm_medis);
                ps.setString(2, Valid.SetTgl(DTPCari1.getSelectedItem() + "") + " 00:00:00");
                ps.setString(3, Valid.SetTgl(DTPCari2.getSelectedItem() + "") + " 23:59:59");
                ps.setString(4, keyword);
                ps.setString(5, keyword);
                ps.setString(6, keyword);
                ps.setString(7, keyword);
                ps.setString(8, keyword);
                rs = ps.executeQuery();
                while (rs.next()) {
                    tabMode.addRow(new Object[]{
                        rs.getString("no_permintaan"), rs.getString("no_rawat"), rs.getString("no_rkm_medis"),
                        rs.getString("nm_pasien"), rs.getString("tanggalkonsultasi"), rs.getString("jenis_permintaan"),
                        rs.getString("kd_dokter"), rs.getString("dokterkonsul"), rs.getString("kd_dokter_dikonsuli"),
                        rs.getString("dokterdikonsuli"), rs.getString("diagnosakerjakonsul"), rs.getString("uraian_konsultasi"),
                        rs.getString("tanggaljawaban"), rs.getString("diagnosakerjajawaban"), rs.getString("uraian_jawaban")
                    });
                }
            } catch(Exception e){
                System.out.println("Notif : " + e);
            } finally{
                if(rs != null){
                    rs.close();
                }
                if(ps != null){
                    ps.close();
                }
            }
        } catch (Exception e) {
            System.out.println("Notifikasi : " + e);
        }
        LCount.setText("" + tabMode.getRowCount());
    }

    private void getData() {
        if (tbRiwayat.getSelectedRow() != -1) {
            StringBuilder detail = new StringBuilder();
            
            String tanggalKonsul = tbRiwayat.getValueAt(tbRiwayat.getSelectedRow(), 4).toString();
            String jenisPermintaan = tbRiwayat.getValueAt(tbRiwayat.getSelectedRow(), 5).toString();
            String dokterKonsul = tbRiwayat.getValueAt(tbRiwayat.getSelectedRow(), 7).toString();
            String dokterDikonsuli = tbRiwayat.getValueAt(tbRiwayat.getSelectedRow(), 9).toString();
            String diagnosaKonsul = tbRiwayat.getValueAt(tbRiwayat.getSelectedRow(), 10).toString();
            String uraianKonsul = tbRiwayat.getValueAt(tbRiwayat.getSelectedRow(), 11).toString();
            
            String tanggalJawab = tbRiwayat.getValueAt(tbRiwayat.getSelectedRow(), 12) != null ? tbRiwayat.getValueAt(tbRiwayat.getSelectedRow(), 12).toString() : "Belum Dijawab";
            String diagnosaJawab = tbRiwayat.getValueAt(tbRiwayat.getSelectedRow(), 13) != null ? tbRiwayat.getValueAt(tbRiwayat.getSelectedRow(), 13).toString() : "-";
            String uraianJawab = tbRiwayat.getValueAt(tbRiwayat.getSelectedRow(), 14) != null ? tbRiwayat.getValueAt(tbRiwayat.getSelectedRow(), 14).toString() : "-";

            detail.append("---------------------------------------------------------- PERMINTAAN KONSULTASI ----------------------------------------------------------\n");
            detail.append("Tanggal         : ").append(tanggalKonsul).append("\n");
            detail.append("Jenis           : ").append(jenisPermintaan).append("\n");
            detail.append("Dokter Konsul   : ").append(dokterKonsul).append("\n");
            detail.append("Kepada          : ").append(dokterDikonsuli).append("\n\n");
            detail.append("Diagnosa Kerja  : ").append(diagnosaKonsul).append("\n");
            detail.append("Uraian          :\n").append(uraianKonsul).append("\n\n");
            detail.append("------------------------------------------------------------ JAWABAN KONSULTASI ------------------------------------------------------------\n");
            detail.append("Tanggal         : ").append(tanggalJawab).append("\n");
            detail.append("Oleh            : ").append(dokterDikonsuli).append("\n\n");
            detail.append("Diagnosa Kerja  : ").append(diagnosaJawab).append("\n");
            detail.append("Jawaban         :\n").append(uraianJawab).append("\n");
            
            DetailKonsultasi.setText(detail.toString());
        }
    }

    public void setNoRm(String norm, String nama) {
        this.no_rkm_medis = norm;
        TNoRM.setText(norm);
        TPasien.setText(nama);
        tampil();
        
        // Otomatis pilih baris pertama dan tampilkan detail jika ada data
        if(tabMode.getRowCount() > 0){
            tbRiwayat.setRowSelectionInterval(0, 0);
            getData();
        }
    }
}

