

package wa;

import fungsi.koneksiDBSalim;
import fungsi.koneksiDB;
import bridging.koneksiDBWa;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.WahaClient;
import fungsi.WagolangClient;
import fungsi.WagolangClient;
import java.awt.event.KeyEvent;
import java.sql.Connection; 
import java.util.Date; 
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.ProtocolException;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import fungsi.akses;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.BorderFactory;
import javax.swing.SwingUtilities;
import javax.swing.border.TitledBorder;
import wa.WhatsappMasterTemplate;
import wa.WhatsappTemplate;
/**
 *
 * @author perpustakaan
 */
public class WhatsappKirimFonnte extends javax.swing.JDialog {
    
    private Connection koneksi = koneksiDB.condb();
    private Connection koneksiwa;
    private sekuel Sequel = new sekuel();
    private validasi Valid = new validasi();
    private PreparedStatement ps;
    private ResultSet rs;
    private WhatsappTemplate templateWA = new WhatsappTemplate(null,false);
    
    private WhatsappTemplate pasien=new WhatsappTemplate(null,false);

    private static final long GATEWAY_CHECK_INTERVAL_MS = 30000L;
    private static final String BASE_FRAME_TITLE = ":: Kirim Whatsapp ::";
    private long lastGatewayCheckAt = 0L;
    
//    private WhatsappMasterTemplate whatsapptemp=new WhatsappMasterTemplate(null,false);
    private WhatsappRiwayat whastappriwayat=new WhatsappRiwayat(null,false);
    

    /** Creates new form DlgPemberianObat
     * @param parent
     * @param modal */
    public WhatsappKirimFonnte(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setLocation(8,1);
        setSize(885,674);
        
        //TCatatan.setText(TCatatan); 
//        TPesan.setLineWrap(true);
//        TPesan.setWrapStyleWord(true); 
         
         
        
        WhatsappTemplate template = new WhatsappTemplate(null, false); 
        template.addWindowListener(new WindowAdapter() {
            @Override
            public void windowOpened(WindowEvent e) {
                TPoli.setText("Window Opened");
            }

            @Override
            public void windowClosing(WindowEvent e) {
                TPoli.setText("Window Closing");
            }

            @Override
            public void windowClosed(WindowEvent e) {
                TPoli.setText("Window Closed");
            }
        });
        
        
        
        
        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // </editor-fold>
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        FormInput = new widget.PanelBiasa();
        Scroll3 = new widget.ScrollPane();
        TPesan = new widget.TextArea();
        BtnTemplate = new widget.Button();
        BtnKirim = new widget.Button();
        BtnKeluar = new widget.Button();
        BtnTemplate1 = new widget.Button();
        NoHp = new javax.swing.JTextField();
        TDokter = new javax.swing.JTextField();
        TPasien = new javax.swing.JTextField();
        TNoRM = new javax.swing.JTextField();
        NoReg = new javax.swing.JTextField();
        TPoli = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        DTPReg = new widget.Tanggal();
        jLabel6 = new javax.swing.JLabel();
        BtnKeluar1 = new widget.Button();
        jLabel5 = new javax.swing.JLabel();
        TglAsuhan = new widget.Tanggal();
        label11 = new widget.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        internalFrame1.setBackground(new java.awt.Color(51, 51, 255));
        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(":: Kirim Whatsapp ::"));
        internalFrame1.setForeground(new java.awt.Color(153, 153, 255));
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setPreferredSize(new java.awt.Dimension(950, 200));
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        FormInput.setName("FormInput"); // NOI18N
        FormInput.setPreferredSize(new java.awt.Dimension(950, 200));
        FormInput.setWarnaAtas(new java.awt.Color(255, 204, 204));
        FormInput.setWarnaBawah(new java.awt.Color(255, 102, 153));
        FormInput.setLayout(null);

        Scroll3.setName("Scroll3"); // NOI18N
        Scroll3.setOpaque(true);

        TPesan.setColumns(20);
        TPesan.setRows(5);
        TPesan.setName("TPesan"); // NOI18N
        Scroll3.setViewportView(TPesan);

        FormInput.add(Scroll3);
        Scroll3.setBounds(20, 50, 680, 200);

        BtnTemplate.setBackground(new java.awt.Color(204, 0, 51));
        BtnTemplate.setForeground(new java.awt.Color(255, 255, 255));
        BtnTemplate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/chat1.png"))); // NOI18N
        BtnTemplate.setMnemonic('G');
        BtnTemplate.setText("Template");
        BtnTemplate.setToolTipText("");
        BtnTemplate.setGlassColor(new java.awt.Color(255, 255, 255));
        BtnTemplate.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BtnTemplate.setName("BtnTemplate"); // NOI18N
        BtnTemplate.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnTemplate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTemplateActionPerformed(evt);
            }
        });
        BtnTemplate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnTemplateKeyPressed(evt);
            }
        });
        FormInput.add(BtnTemplate);
        BtnTemplate.setBounds(20, 260, 110, 30);

        BtnKirim.setForeground(new java.awt.Color(255, 255, 255));
        BtnKirim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/wa.png"))); // NOI18N
        BtnKirim.setMnemonic('T');
        BtnKirim.setText("Kirim");
        BtnKirim.setToolTipText("Alt+T");
        BtnKirim.setGlassColor(new java.awt.Color(255, 255, 255));
        BtnKirim.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BtnKirim.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BtnKirim.setName("BtnKirim"); // NOI18N
        BtnKirim.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKirimActionPerformed(evt);
            }
        });
        BtnKirim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKirimKeyPressed(evt);
            }
        });
        FormInput.add(BtnKirim);
        BtnKirim.setBounds(290, 260, 90, 30);

        BtnKeluar.setBorder(null);
        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/x.png"))); // NOI18N
        BtnKeluar.setMnemonic('T');
        BtnKeluar.setToolTipText("Alt+T");
        BtnKeluar.setGlassColor(new java.awt.Color(204, 255, 204));
        BtnKeluar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BtnKeluar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.setRoundRect(false);
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        FormInput.add(BtnKeluar);
        BtnKeluar.setBounds(660, 0, 30, 30);

        BtnTemplate1.setForeground(new java.awt.Color(255, 255, 255));
        BtnTemplate1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/chat2.png"))); // NOI18N
        BtnTemplate1.setMnemonic('G');
        BtnTemplate1.setText("Riwayat Chat");
        BtnTemplate1.setToolTipText("");
        BtnTemplate1.setGlassColor(new java.awt.Color(255, 255, 255));
        BtnTemplate1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BtnTemplate1.setName("BtnTemplate1"); // NOI18N
        BtnTemplate1.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnTemplate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTemplate1ActionPerformed(evt);
            }
        });
        BtnTemplate1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnTemplate1KeyPressed(evt);
            }
        });
        FormInput.add(BtnTemplate1);
        BtnTemplate1.setBounds(140, 260, 140, 30);

        NoHp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        NoHp.setBorder(null);
        NoHp.setName("NoHp"); // NOI18N
        FormInput.add(NoHp);
        NoHp.setBounds(460, 10, 170, 17);

        TDokter.setEditable(false);
        TDokter.setBackground(new java.awt.Color(255, 255, 255));
        TDokter.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TDokter.setBorder(null);
        TDokter.setName("TDokter"); // NOI18N
        FormInput.add(TDokter);
        TDokter.setBounds(210, 30, 180, 17);

        TPasien.setEditable(false);
        TPasien.setBackground(new java.awt.Color(255, 255, 255));
        TPasien.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TPasien.setBorder(null);
        TPasien.setName("TPasien"); // NOI18N
        FormInput.add(TPasien);
        TPasien.setBounds(210, 10, 180, 17);

        TNoRM.setEditable(false);
        TNoRM.setBackground(new java.awt.Color(255, 255, 255));
        TNoRM.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TNoRM.setBorder(null);
        TNoRM.setName("TNoRM"); // NOI18N
        FormInput.add(TNoRM);
        TNoRM.setBounds(80, 10, 70, 17);

        NoReg.setEditable(false);
        NoReg.setBackground(new java.awt.Color(255, 255, 255));
        NoReg.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        NoReg.setBorder(null);
        NoReg.setName("NoReg"); // NOI18N
        FormInput.add(NoReg);
        NoReg.setBounds(80, 30, 71, 17);

        TPoli.setEditable(false);
        TPoli.setBackground(new java.awt.Color(255, 255, 255));
        TPoli.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TPoli.setBorder(null);
        TPoli.setName("TPoli"); // NOI18N
        FormInput.add(TPoli);
        TPoli.setBounds(460, 30, 170, 17);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(123, 36, 28));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Poli :  ");
        jLabel1.setName("jLabel1"); // NOI18N
        FormInput.add(jLabel1);
        jLabel1.setBounds(400, 30, 60, 17);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(123, 36, 28));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Antrian :  ");
        jLabel2.setName("jLabel2"); // NOI18N
        FormInput.add(jLabel2);
        jLabel2.setBounds(20, 30, 60, 17);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Ubah Tanggal Kontrol :");
        jLabel3.setName("jLabel3"); // NOI18N
        FormInput.add(jLabel3);
        jLabel3.setBounds(450, 250, 150, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(123, 36, 28));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("No RM :  ");
        jLabel4.setName("jLabel4"); // NOI18N
        FormInput.add(jLabel4);
        jLabel4.setBounds(20, 10, 60, 17);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(123, 36, 28));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("No WA :  ");
        jLabel7.setName("jLabel7"); // NOI18N
        FormInput.add(jLabel7);
        jLabel7.setBounds(400, 10, 60, 17);

        DTPReg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "24-11-2024" }));
        DTPReg.setDisplayFormat("dd-MM-yyyy");
        DTPReg.setName("DTPReg"); // NOI18N
        DTPReg.setOpaque(false);
        DTPReg.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DTPRegItemStateChanged(evt);
            }
        });
        DTPReg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DTPRegKeyPressed(evt);
            }
        });
        FormInput.add(DTPReg);
        DTPReg.setBounds(610, 250, 90, 23);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(123, 36, 28));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Nama :  ");
        jLabel6.setName("jLabel6"); // NOI18N
        FormInput.add(jLabel6);
        jLabel6.setBounds(150, 10, 60, 17);

        BtnKeluar1.setBorder(null);
        BtnKeluar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/x.png"))); // NOI18N
        BtnKeluar1.setMnemonic('T');
        BtnKeluar1.setToolTipText("Alt+T");
        BtnKeluar1.setGlassColor(new java.awt.Color(204, 255, 204));
        BtnKeluar1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BtnKeluar1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BtnKeluar1.setName("BtnKeluar1"); // NOI18N
        BtnKeluar1.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar1.setRoundRect(false);
        BtnKeluar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluar1ActionPerformed(evt);
            }
        });
        BtnKeluar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluar1KeyPressed(evt);
            }
        });
        FormInput.add(BtnKeluar1);
        BtnKeluar1.setBounds(660, 0, 30, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(123, 36, 28));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Dokter :  ");
        jLabel5.setName("jLabel5"); // NOI18N
        FormInput.add(jLabel5);
        jLabel5.setBounds(150, 30, 60, 17);

        TglAsuhan.setForeground(new java.awt.Color(255, 255, 255));
        TglAsuhan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "24-11-2024 20:25:05" }));
        TglAsuhan.setDisplayFormat("dd-MM-yyyy HH:mm:ss");
        TglAsuhan.setName("TglAsuhan"); // NOI18N
        TglAsuhan.setOpaque(false);
        TglAsuhan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TglAsuhanKeyPressed(evt);
            }
        });
        FormInput.add(TglAsuhan);
        TglAsuhan.setBounds(570, 280, 130, 20);

        label11.setForeground(new java.awt.Color(255, 255, 255));
        label11.setText("Tanggal :");
        label11.setName("label11"); // NOI18N
        label11.setPreferredSize(new java.awt.Dimension(70, 23));
        FormInput.add(label11);
        label11.setBounds(490, 280, 60, 20);

        internalFrame1.add(FormInput, java.awt.BorderLayout.CENTER);
        FormInput.getAccessibleContext().setAccessibleName("");
        FormInput.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);
        internalFrame1.getAccessibleContext().setAccessibleDescription("::[ Kirim Pesan Whatsapp ]::");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
}//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            dispose();
        }
}//GEN-LAST:event_BtnKeluarKeyPressed

private void BtnTemplateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTemplateActionPerformed

    try {
        WhatsappTemplate whatsappTemplate = new WhatsappTemplate(null, false);
        // whatsappTemplate.setNoRawat(TNoRM.getText());
        whatsappTemplate.tampil();
        whatsappTemplate.setSize(internalFrame1.getWidth() - 20, internalFrame1.getHeight() - 20);
        whatsappTemplate.setLocationRelativeTo(internalFrame1);
        whatsappTemplate.setVisible(true);
    } catch (Exception e) {
        // Handle exception (jika ada)
        e.printStackTrace(); // Gantilah ini dengan penanganan yang sesuai
    }
           
}//GEN-LAST:event_BtnTemplateActionPerformed

private void BtnTemplateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnTemplateKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
           
        }
}//GEN-LAST:event_BtnTemplateKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        TPesan.requestFocus();
        updateGatewayStatusAsync();
    }//GEN-LAST:event_formWindowActivated

    private void BtnKirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKirimActionPerformed
        String gateway = koneksiDB.WAGATEWAY().trim().toLowerCase();
        if ("waha".equals(gateway)) {
            KirimWaWaha();
        } else if ("golang".equals(gateway) || "wagolang".equals(gateway)) {
            KirimWaGolang();
        } else {
            KirimWaDelphi();
        }
    }//GEN-LAST:event_BtnKirimActionPerformed

    private void BtnKirimKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKirimKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnKirimKeyPressed

    private void BtnTemplate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTemplate1ActionPerformed
        // TODO add your handling code here:
                                                    
whastappriwayat.setNoRawat(TNoRM.getText());
whastappriwayat.tampil();
whastappriwayat.setSize(internalFrame1.getWidth()-20,internalFrame1.getHeight()-20);
whastappriwayat.setLocationRelativeTo(internalFrame1);
whastappriwayat.setVisible(true);
    }//GEN-LAST:event_BtnTemplate1ActionPerformed

    private void BtnTemplate1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnTemplate1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnTemplate1KeyPressed

    private void DTPRegItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DTPRegItemStateChanged
        
    }//GEN-LAST:event_DTPRegItemStateChanged

    private void DTPRegKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DTPRegKeyPressed
         
    }//GEN-LAST:event_DTPRegKeyPressed

    private void BtnKeluar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnKeluar1ActionPerformed

    private void BtnKeluar1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluar1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnKeluar1KeyPressed

    private void TglAsuhanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TglAsuhanKeyPressed
        //        Valid.pindah(evt,BtnDPJP,MacamKasus);
    }//GEN-LAST:event_TglAsuhanKeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            WhatsappKirimFonnte dialog = new WhatsappKirimFonnte(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                     System.out.println("Jendela ditutup");
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnKeluar;
    private widget.Button BtnKeluar1;
    private widget.Button BtnKirim;
    private widget.Button BtnTemplate;
    private widget.Button BtnTemplate1;
    private widget.Tanggal DTPReg;
    private widget.PanelBiasa FormInput;
    private javax.swing.JTextField NoHp;
    private javax.swing.JTextField NoReg;
    private widget.ScrollPane Scroll3;
    private javax.swing.JTextField TDokter;
    private javax.swing.JTextField TNoRM;
    private javax.swing.JTextField TPasien;
    private widget.TextArea TPesan;
    private javax.swing.JTextField TPoli;
    private widget.Tanggal TglAsuhan;
    private widget.InternalFrame internalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private widget.Label label11;
    // End of variables declaration//GEN-END:variables
    

    private void isPsien() {
//        Sequel.cariIsi("select pasien.nm_pasien from pasien where pasien.no_rkm_medis=? ",TPasien,TNoRM.getText());
//        Sequel.cariIsi("select pasien.no_tlp from pasien where pasien.no_rkm_medis=? ",NoHp,TNoRM.getText());
    
     }

    public void setNoRm(String norm, String noreg, String poli, String dokter, Date tanggal) {
         TNoRM.setText(norm);   
         NoReg.setText(noreg); 
         TPoli.setText(poli);
         TDokter.setText(dokter);
         DTPReg.setDate(tanggal); 
        Sequel.cariIsi("select pasien.nm_pasien from pasien where pasien.no_rkm_medis=? ",TPasien,TNoRM.getText());
        Sequel.cariIsi("select pasien.no_tlp from pasien where pasien.no_rkm_medis=? ",NoHp,TNoRM.getText());
        isPsien();   
//        Sequel.cariIsi("select catatan_pasien.catatan from catatan_pasien where catatan_pasien.no_rkm_medis=?",TCatatan,TNoRM.getText());       
    }
    
    
    public void setPesan(String dataTemplate) {
         TPesan.setText(dataTemplate); 
        isPsien();   
//        Sequel.cariIsi("select catatan_pasien.catatan from catatan_pasien where catatan_pasien.no_rkm_medis=?",TCatatan,TNoRM.getText());       
    }
    
 
    
    public void isCek(){
        BtnKirim.setEnabled(true);
        BtnTemplate.setEnabled(true);
        BtnTemplate.setEnabled(true);
       
        
    }
    
    private void KirimWaDelphi()    {
        Connection koneksiwa = koneksiDBWa.condb();
        PreparedStatement ps = null;
        
        String target = NoHp.getText() + "|" + TPasien.getText() + "|" + TNoRM.getText() + "|" + NoReg.getText() + "|" + TPoli.getText() + "|" + TDokter.getText() + "|" + DTPReg.getSelectedItem();
                String message = TPesan.getText();
                String pesan = TPesan.getText();
                String countryCode = "62"; //optional
                String tanggal = (String) DTPReg.getSelectedItem();
                message = message.replace("{nama}", TPasien.getText())
                        .replace("{rm}", TNoRM.getText())
                        .replace("{antrian}", NoReg.getText())
                        .replace("{poli}", TPoli.getText())
                        .replace("{dokter}", TDokter.getText())
                        .replace("{tanggal}", tanggal);
                
                pesan = pesan.replace("{nama}", TPasien.getText())
                        .replace("{rm}", TNoRM.getText())
                        .replace("{antrian}", NoReg.getText())
                        .replace("{poli}", TPoli.getText())
                        .replace("{dokter}", TDokter.getText())
                        .replace("{tanggal}", tanggal)
                        .replace("*", "")
                        .replace("_", "")
                        .replace("{", "")
                        .replace("}", "");
                        
               //menggabungkan parameter ke dalam format yang sesuai untuk dikirim
               String postData = message;
               
          
       try {
           String sql = "INSERT INTO wa_outbox (NOMOR, NOWA, PESAN, TANGGAL_JAM, STATUS, SOURCE , SENDER, SUCCESS, RESPONSE, REQUEST, TYPE, FILE) "
                        + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
           ps = koneksiwa.prepareStatement(sql);
           ps.setLong(1, 0);
           ps.setString(2, NoHp.getText() + "@c.us"); //NOWA
           ps.setString(3, postData); //PESAN
           ps.setTimestamp(4, java.sql.Timestamp.valueOf(
                        Valid.SetTgl(TglAsuhan.getSelectedItem().toString()) + " "
                        + TglAsuhan.getSelectedItem().toString().substring(11, 19))); //TGL_JAM
           ps.setString(5, "ANTRIAN");  //STATUS
           ps.setString(6, "RS2024");   //SOURCE
           ps.setString(7, "NODEJS");   //SENDER
           ps.setString(8, "");         //SUCCESS
           ps.setString(9, "");         //RESPONSE
           ps.setString(10, "");        //REQUEST
           ps.setString(11, "TEXT");    //TYPE
           ps.setString(12, "");        //FILE
           
           ps.executeUpdate();   
       } catch (Exception e) {
           System.out.println("Notif : " + e);
       } finally {
           try {
               if (ps != null) {
                   ps.close();
               }
               if (koneksiwa != null) {
//                   koneksiwa.close();
               }
           } catch (Exception ex) {
               System.out.println("Error closing resources: " + ex); 
           }   
     }             
            JOptionPane.showMessageDialog(null, "Berhasil Mengirim Pesan !!", "Success", JOptionPane.INFORMATION_MESSAGE);                                       
                
    }

    private void KirimWaWaha() {
        String tanggal = (String) DTPReg.getSelectedItem();
        String rawPhone = NoHp.getText() == null ? "" : NoHp.getText().trim();
        rawPhone = rawPhone.replace("|", "").replace(" ", "");

        String message = TPesan.getText();
        message = message.replace("{nama}", TPasien.getText())
                .replace("{rm}", TNoRM.getText())
                .replace("{antrian}", NoReg.getText())
                .replace("{poli}", TPoli.getText())
                .replace("{dokter}", TDokter.getText())
                .replace("{tanggal}", tanggal);

        WahaClient.Result result = WahaClient.sendText(rawPhone, message);
        if (result.ok) {
            JOptionPane.showMessageDialog(null, "Berhasil Mengirim Pesan !!", "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            String errMsg = result.error;
            if (result.responseBody != null && !result.responseBody.isEmpty()) {
                errMsg += " | " + result.responseBody;
            }
            JOptionPane.showMessageDialog(null, "Gagal mengirim: " + errMsg, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void KirimWaGolang() {
        String tanggal = (String) DTPReg.getSelectedItem();
        String rawPhone = NoHp.getText() == null ? "" : NoHp.getText().trim();
        rawPhone = rawPhone.replace("|", "").replace(" ", "");

        String message = TPesan.getText();
        message = message.replace("{nama}", TPasien.getText())
                .replace("{rm}", TNoRM.getText())
                .replace("{antrian}", NoReg.getText())
                .replace("{poli}", TPoli.getText())
                .replace("{dokter}", TDokter.getText())
                .replace("{tanggal}", tanggal);

        WagolangClient.Result result = WagolangClient.sendText(rawPhone, message);
        if (result.ok) {
            JOptionPane.showMessageDialog(null, "Berhasil Mengirim Pesan !!", "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            String errMsg = result.error;
            if (result.responseBody != null && !result.responseBody.isEmpty()) {
                errMsg += " | " + result.responseBody;
            }
            JOptionPane.showMessageDialog(null, "Gagal mengirim: " + errMsg, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void updateGatewayStatusAsync() {
        long now = System.currentTimeMillis();
        if (now - lastGatewayCheckAt < GATEWAY_CHECK_INTERVAL_MS) {
            return;
        }
        lastGatewayCheckAt = now;

        String gatewayRaw = koneksiDB.WAGATEWAY();
        String gateway = gatewayRaw == null ? "" : gatewayRaw.trim().toLowerCase();
        String labelGateway = gateway.isEmpty() ? "unknown" : gateway;
        setInternalFrameTitle(BASE_FRAME_TITLE + " | Gateway: " + labelGateway + " (cek...)");

        Thread worker = new Thread(() -> {
            String title = buildGatewayStatusTitle(labelGateway, gateway);
            SwingUtilities.invokeLater(() -> setInternalFrameTitle(title));
        }, "wa-gateway-healthcheck");
        worker.setDaemon(true);
        worker.start();
    }

    private String buildGatewayStatusTitle(String labelGateway, String gateway) {
        if ("waha".equals(gateway)) {
            WahaClient.HealthResult result = WahaClient.check();
            return formatHealthTitle(labelGateway, result.ok, result.latencyMs, result.error);
        }
        if ("golang".equals(gateway) || "wagolang".equals(gateway)) {
            WagolangClient.HealthResult result = WagolangClient.check();
            return formatHealthTitle(labelGateway, result.ok, result.latencyMs, result.error);
        }
        return BASE_FRAME_TITLE + " | Gateway: " + labelGateway + " (tanpa cek)";
    }

    private String formatHealthTitle(String labelGateway, boolean ok, long latencyMs, String error) {
        if (ok) {
            return BASE_FRAME_TITLE + " | Gateway: " + labelGateway + " (OK " + latencyMs + "ms)";
        }
        String detail = error == null || error.trim().isEmpty() ? "ERR" : "ERR " + error.trim();
        if (detail.length() > 60) {
            detail = detail.substring(0, 60) + "...";
        }
        return BASE_FRAME_TITLE + " | Gateway: " + labelGateway + " (" + detail + ")";
    }

    private void setInternalFrameTitle(String title) {
        if (internalFrame1.getBorder() instanceof TitledBorder) {
            TitledBorder border = (TitledBorder) internalFrame1.getBorder();
            border.setTitle(title);
        } else {
            internalFrame1.setBorder(BorderFactory.createTitledBorder(title));
        }
        internalFrame1.repaint();
    }
         
    
}
