CREATE TABLE IF NOT EXISTS asesmen_awal_rawat_inap_medis (
    no_rawat VARCHAR(17) NOT NULL,
    tanggal DATETIME,
    kd_dokter VARCHAR(20),
    sumber_rujukan VARCHAR(120),
    diagnosa_rujukan TEXT,
    anamnesis VARCHAR(30),
    hubungan VARCHAR(50),
    cara_datang VARCHAR(60),
    keluhan_utama TEXT,
    riwayat_penyakit_sekarang TEXT,
    riwayat_penyakit_dahulu TEXT,
    riwayat_pengobatan TEXT,
    riwayat_penyakit_keluarga TEXT,
    riwayat_alergi_obat TEXT,
    kesadaran VARCHAR(30),
    berat_badan VARCHAR(15),
    tinggi_badan VARCHAR(15),
    tekanan_darah VARCHAR(20),
    nadi VARCHAR(15),
    respirasi VARCHAR(15),
    suhu VARCHAR(15),
    spo2 VARCHAR(15),
    pemeriksaan_mata TEXT,
    sistem_saraf TEXT,
    pemeriksaan_tht TEXT,
    pemeriksaan_thoraks TEXT,
    pemeriksaan_abdomen TEXT,
    pemeriksaan_ekstremitas TEXT,
    status_lokalisasi TEXT,
    hasil_laboratorium TEXT,
    hasil_ekg TEXT,
    hasil_radiologi TEXT,
    diagnosis_banding TEXT,
    rencana_kerja_terapi TEXT,
    catatan_penting TEXT,
    dokter_pengkaji VARCHAR(120),
    dokter_dpjp VARCHAR(120),
    PRIMARY KEY (no_rawat),
    KEY kd_dokter (kd_dokter)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
