-- Schema untuk tabel penilaian_medis_igd (lengkap dengan kolom disposisi terbaru)
-- Jalankan: mysql -u root -p < sql/create_penilaian_medis_igd.sql

CREATE DATABASE IF NOT EXISTS rs2024;
USE rs2024;

DROP TABLE IF EXISTS penilaian_medis_igd;

CREATE TABLE penilaian_medis_igd (
  no_rawat          VARCHAR(17)  NOT NULL,
  tanggal           DATETIME     NOT NULL,
  kd_dokter         VARCHAR(20)  NOT NULL,
  anamnesis         ENUM('Autoanamnesis','Alloanamnesis') NOT NULL,
  hubungan          VARCHAR(100) NOT NULL,
  keluhan_utama     VARCHAR(2000) NOT NULL DEFAULT '',
  rps               VARCHAR(2000) NOT NULL,
  rpd               VARCHAR(1000) NOT NULL DEFAULT '',
  rpk               VARCHAR(1000) NOT NULL,
  rpo               VARCHAR(1000) NOT NULL,
  alergi            VARCHAR(100)  NOT NULL DEFAULT '',
  keadaan           ENUM('Sehat','Sakit Ringan','Sakit Sedang','Sakit Berat') NOT NULL,
  gcs               VARCHAR(10)   NOT NULL,
  kesadaran         ENUM('Compos Mentis','Apatis','Somnolen','Sopor','Koma') NOT NULL,
  td                VARCHAR(8)    NOT NULL DEFAULT '',
  nadi              VARCHAR(5)    NOT NULL DEFAULT '',
  rr                VARCHAR(5)    NOT NULL,
  suhu              VARCHAR(5)    NOT NULL DEFAULT '',
  spo               VARCHAR(5)    NOT NULL,
  bb                VARCHAR(5)    NOT NULL DEFAULT '',
  tb                VARCHAR(5)    NOT NULL DEFAULT '',
  kepala            ENUM('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  mata              ENUM('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  gigi              ENUM('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  leher             ENUM('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  thoraks           ENUM('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  abdomen           ENUM('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  genital           ENUM('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  ekstremitas       ENUM('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  ket_fisik         TEXT          NOT NULL,
  ket_lokalis       TEXT          NOT NULL,
  ekg               TEXT          NOT NULL,
  rad               TEXT          NOT NULL,
  lab               TEXT          NOT NULL,
  diagnosis         VARCHAR(500)  NOT NULL,
  tata              TEXT          NOT NULL,
  cara_datang       ENUM('Datang Sendiri','Dikirim oleh Dokter','Puskesmas di antar oleh dokter/polisi') NOT NULL DEFAULT 'Datang Sendiri',
  ket_cara_datang   VARCHAR(200)  NOT NULL DEFAULT '',
  tempat_kecelakaan VARCHAR(150)  NOT NULL DEFAULT '',
  tgl_kecelakaan    VARCHAR(50)   NOT NULL DEFAULT '',
  jam_kecelakaan    VARCHAR(20)   NOT NULL DEFAULT '',
  jenis_kecelakaan  VARCHAR(200)  NOT NULL DEFAULT '',
  bagian1           VARCHAR(150)  NOT NULL DEFAULT '',
  diminta_jam1      VARCHAR(20)   NOT NULL DEFAULT '',
  datang_jam1       VARCHAR(20)   NOT NULL DEFAULT '',
  bagian2           VARCHAR(150)  NOT NULL DEFAULT '',
  diminta_jam2      VARCHAR(20)   NOT NULL DEFAULT '',
  datang_jam2       VARCHAR(20)   NOT NULL DEFAULT '',
  bagian3           VARCHAR(150)  NOT NULL DEFAULT '',
  diminta_jam3      VARCHAR(20)   NOT NULL DEFAULT '',
  datang_jam3       VARCHAR(20)   NOT NULL DEFAULT '',
  observasi         ENUM('Ya','Tidak') NOT NULL DEFAULT 'Tidak',
  dipulangkan       ENUM('Ya','Tidak') NOT NULL DEFAULT 'Tidak',
  paps_dirujuk      ENUM('Ya','Tidak') NOT NULL DEFAULT 'Tidak',
  dirujuk           ENUM('Ya','Tidak') NOT NULL DEFAULT 'Tidak',
  dirujuk_ke        VARCHAR(150)  NOT NULL DEFAULT '',
  rawat_inap        ENUM('Ya','Tidak') NOT NULL DEFAULT 'Tidak',
  rawat_inap_ke     VARCHAR(150)  NOT NULL DEFAULT '',
  keadaan_sembuh    ENUM('Ya','Tidak') NOT NULL DEFAULT 'Tidak',
  sembuh_td         VARCHAR(8)    NOT NULL DEFAULT '',
  sembuh_nadi       VARCHAR(5)    NOT NULL DEFAULT '',
  sembuh_rr         VARCHAR(5)    NOT NULL DEFAULT '',
  sembuh_suhu       VARCHAR(5)    NOT NULL DEFAULT '',
  sembuh_kesadaran  VARCHAR(100)  NOT NULL DEFAULT '',
  keadaan_membaik   ENUM('Ya','Tidak') NOT NULL DEFAULT 'Tidak',
  membaik_td        VARCHAR(8)    NOT NULL DEFAULT '',
  membaik_nadi      VARCHAR(5)    NOT NULL DEFAULT '',
  membaik_rr        VARCHAR(5)    NOT NULL DEFAULT '',
  membaik_suhu      VARCHAR(5)    NOT NULL DEFAULT '',
  membaik_kesadaran VARCHAR(100)  NOT NULL DEFAULT '',
  perawatan_lanjut  ENUM('Ya','Tidak') NOT NULL DEFAULT 'Tidak',
  lanjut_td         VARCHAR(8)    NOT NULL DEFAULT '',
  lanjut_nadi       VARCHAR(5)    NOT NULL DEFAULT '',
  lanjut_rr         VARCHAR(5)    NOT NULL DEFAULT '',
  lanjut_suhu       VARCHAR(5)    NOT NULL DEFAULT '',
  lanjut_kesadaran  VARCHAR(100)  NOT NULL DEFAULT '',
  meninggal         ENUM('Ya','Tidak') NOT NULL DEFAULT 'Tidak',
  PRIMARY KEY (no_rawat),
  KEY kd_dokter (kd_dokter),
  CONSTRAINT penilaian_medis_igd_ibfk_1 FOREIGN KEY (no_rawat) REFERENCES reg_periksa (no_rawat) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT penilaian_medis_igd_ibfk_2 FOREIGN KEY (kd_dokter) REFERENCES dokter (kd_dokter) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
